name: AzureDevopsPipelineWorkflow

on:
  push:
    branches: none
  pull_request:
    branches: none


# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
    build:
        name: Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/AndrejaLearning/WebApp
            azure-pipeline-name: FirstWeb'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
